### ISSUE TITLE
Remove references to `django_starter`.

### ISSUE THREAD

**Issue by Zoltu** [flowfree/django_starter#2]
There are a number of references to `django_starter` in this project, including a couple folder names.  These should probably be swapped out with `magic_repo_name_magic` so when the user creates a new project from this as a template all their stuff will be named after their project, rather than some of it named `django_starter`.  The goal is that when a user clones from template they won't have to go and do any cleanup to get the project personalized, it will all be done for them by RepoCreator.

**Comment by flowfree** [comment]
Removed all references to `django_starter` in b581ff55078e9bc49e6f54244c2d3583db6374bc
